"""レビュー結果をプルリクエストのコメントとして反映する.

push のたびに新しいコメントを積むと読みにくいので、
目印を埋めた自分のコメントを探して書き換える。
"""

from __future__ import annotations

import json
import logging
import urllib.error
import urllib.request

log = logging.getLogger(__name__)

MARKER = "<!-- claude-pr-review -->"
API_ROOT = "https://api.github.com"


def render(review: str, choice, head_sha: str) -> str:
    """コメント本文を組み立てる."""
    body = review.strip() or "(レビュー結果が空でした)"
    return "\n".join(
        [
            MARKER,
            "## Claude によるレビュー",
            "",
            body,
            "",
            "---",
            f"モデル: `{choice.model}` / effort: `{choice.effort}`  ",
            f"選定理由: {choice.reason}  ",
            f"対象: `{head_sha[:7]}`",
            "",
            "_Generated by [Claude Code](https://claude.ai/code)_",
        ]
    )


def _request(method: str, url: str, token: str, payload: dict | None = None):
    data = json.dumps(payload).encode() if payload is not None else None
    request = urllib.request.Request(url, data=data, method=method)
    request.add_header("Authorization", f"Bearer {token}")
    request.add_header("Accept", "application/vnd.github+json")
    request.add_header("X-GitHub-Api-Version", "2022-11-28")
    if data is not None:
        request.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.loads(response.read() or b"null")


def find_existing(repo: str, pr_number: int, token: str, requester=_request) -> int | None:
    """目印付きの既存コメントを探す."""
    url = f"{API_ROOT}/repos/{repo}/issues/{pr_number}/comments?per_page=100"
    try:
        comments = requester("GET", url, token) or []
    except urllib.error.URLError as exc:
        log.warning("既存コメントを取得できませんでした: %s", exc)
        return None
    for comment in comments:
        if MARKER in (comment.get("body") or ""):
            return comment.get("id")
    return None


def publish(repo: str, pr_number: int, token: str, body: str, requester=_request) -> str:
    """既存があれば書き換え、無ければ新規に投稿する. 戻り値は行った操作."""
    existing = find_existing(repo, pr_number, token, requester)
    if existing is not None:
        requester(
            "PATCH",
            f"{API_ROOT}/repos/{repo}/issues/comments/{existing}",
            token,
            {"body": body},
        )
        return "updated"
    requester(
        "POST",
        f"{API_ROOT}/repos/{repo}/issues/{pr_number}/comments",
        token,
        {"body": body},
    )
    return "created"
